### PR TITLE
changed quality to has_modifier

### PR DESCRIPTION
**Pull request by Clare72**

### CODE REVIEW

**Comment by matentzn** [comment]
I also changed the towards relation to the official one.

**Comment by matentzn** [comment]
@dosumis can you review this soonish? Should be fine!

**Comment by dosumis** [comment]
Looks fine. Can you merge? I still don't have write access to repo.  @Clare72  could you  fix?

**Comment by Clare72** [comment]
@dosumis - settings say admin access is awaiting your response

**Comment by dosumis** [comment]
Ooops - sorry.  Now accepted.

**Pull request merged**
